# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Angelene Manlo
title: Angelene Manalo
email: angelenelm@gmail.com
description: Front-end developer and designer powered by empathy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://angelenelm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
social:
  - title: email
    url: mailto:angelenelm@gmail.com
  - title: twitter
    url: https://twitter.com/bulbasaurus_
  - title: instagram
    url: https://instagram.com/angelenelm_
  - title: linkedin
    url: https://linkedin.com/in/angelenelm
  - title: github
    url: https://github.com/angelenelm

collections:
  pages:
    output: true
    permalink: /:title

plugins:
  - jekyll-sitemap

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
